### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by tomoino** [tomoino/PyTorch-Project-Template#15]
## TODO
- [x] Refactor data #18 
    - [x] Add base dataset
    - [x] Add base sampler
- [x] Refactor trainer
    - [x] Move metrics to trainers/metrics
    - [x] Refactor default trainer
    - [x] Add default metrics
    - [x] Add base metrics
- [x] Refactor models
    - [x] Move optimizer to trainers/optimizer
    - [x] Move criterion to trainers/criterion
