### ISSUE TITLE
Refactoring for data modules

### ISSUE THREAD

**Issue by tomoino** [tomoino/PyTorch-Project-Template#18]
# TODO
- [x] Refactor data/init
- [x] Add base dataset
- [x] Add base sampler

# Parent issue
#15
