### ISSUE TITLE
Refactoring for trainers and metrics

### ISSUE THREAD

**Issue by tomoino** [tomoino/PyTorch-Project-Template#20]
## TODO
- [x] Refactor trainer
    - [x] Move metrics to trainers/metrics
    - [x] Refactor default trainer
    - [x] Add default metrics
    - [x] Add base metrics

## Parent issue
#15
